---
name: Action Pin Diff
on:
  pull_request:
    paths:
      - ".github/workflows/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  pin-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: vvoland/gha-pin-diff@b347c06d2ec145ae49aa4ef9a39c3baa0140a822 # v1
